name: pyod
dependencies:
  - keras
  - matplotlib
  - nose
  - numba
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tensorflow
  - xgboost
  - pip
  - pip:
      - suod
      - combo
      - statsmodels

