# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# Adapted from https://github.com/NeuralEnsemble/python-neo
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
      - test-3.9

jobs:
  test-3.6:
    docker:
      - image: circleci/python:3.6-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-py36-dependencies-{{ checksum "requirements_ci.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-py36-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_ci.txt
            pip install pytest
            pip install pytest-cov


      - save_cache:
          paths:
            - ./venv
          key: v2-py36-dependencies-{{ checksum "requirements.txt" }}


      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
          no_output_timeout: 30m


  test-3.7:
    docker:
      - image: circleci/python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-py37-dependencies-{{ checksum "requirements_ci.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-py37-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_ci.txt
            pip install pytest
            pip install pytest-cov


      - save_cache:
          paths:
            - ./venv
          key: v2-py37-dependencies-{{ checksum "requirements.txt" }}


      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
          no_output_timeout: 60m

      - store_artifacts:
          path: test-reports
          destination: test-reports


  test-3.8:
    docker:
      - image: cimg/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-py38-dependencies-{{ checksum "requirements_ci.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-py38-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_ci.txt
            pip install pytest
            pip install pytest-cov


      - save_cache:
          paths:
            - ./venv
          key: v2-py38-dependencies-{{ checksum "requirements.txt" }}


      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
          no_output_timeout: 30m

  test-3.9:
    docker:
      - image: cimg/python:3.9

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-py39-dependencies-{{ checksum "requirements_ci.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-py39-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_ci.txt
            pip install pytest
            pip install pytest-cov


      - save_cache:
          paths:
            - ./venv
          key: v2-py39-dependencies-{{ checksum "requirements.txt" }}


      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
          no_output_timeout: 30m


